"""Prompt templates for the analyzer agent."""

from inference.utils.grid_utils import ARC_COLOR_LEGEND

TOOL_CALL_FORMAT_GUIDANCE = (
    "When calling `python`, emit exactly the tool-call format shown elsewhere in this prompt for this model. "
    "Use only that format; do not add markdown fences, prose wrappers, or alternate tool-call syntax. "
    "Do not quote or place tool-call markup inside explanatory text; when you decide to call the tool, emit the tool call itself."
)

GAME_OVERVIEW_ADDENDUM = (
    "\n\nGame overview:\n"
    "- You are solving a multi-level grid puzzle game. \n"
    "- You are called repeatedly over the course of a run. Treat each turn as one observe-plan-act cycle: re-understand the current state from the newest frame, update your working world model in Python, choose the next best action or short sequence against the goal as currently understood, execute it, and expect to re-evaluate on the next turn from the updated state.\n"
    "- Your job is to solve the entire game by clearing every level, not just the current screen.\n"
    "- Levels often build on earlier mechanics, but layouts and interactions can still change between levels.\n"
    "- Optimize for as few in-game actions as possible while still being reliable.\n"
    "- In this environment, boards are presented as 64 x 64 color grids rendered with ARC color symbols.\n"
    f"- Color legend: {ARC_COLOR_LEGEND}.\n"
)

NAV_HELPER_ADDENDUM = (
    "\n\nNavigation helper (`nav`, rebuilt from `transitions` every call):\n"
    "- `nav.summary()` returns a compact text: the avatar (object that your movement actions move), the learned "
    "move deltas per action, floor/wall knowledge, a shrinking action gauge if present, candidate targets "
    "(non-floor objects with (row, col) and BFS path length) and the nearest unexplored block.\n"
    "- `nav.map()` returns a coarse map (one char per movement cell; P=avatar, #=known wall).\n"
    "- `nav.path_to(row, col)` returns a list of action names that walks the avatar to the block containing that pixel "
    "over known-walkable cells (last step may enter any colour), or None if unreachable/unlearned. Pass it straight to `action(...)`.\n"
    "- `nav.frontier()` gives (row, col) of the nearest unexplored walkable block; `nav.targets()` the target list; "
    "`nav.moves`, `nav.avatar()`, `nav.gauge()` the raw facts. `nav` is None until a frame exists.\n"
    "- The helper learns only from real moves: press each movement action once or twice first, then trust `nav.path_to` "
    "instead of hand-written step sequences. Prefer visiting unvisited targets nearest-first; the level goal is usually one of them.\n"
)

ADVISOR_ADDENDUM = (
    "\n\nAdvisor ensemble:\n"
    "- Each user turn may include an `Advisor ensemble` block: short opinions from several smaller, independent models "
    "that saw a compact rendering of the same state (hypothesis, evidence, recommended actions, confidence, warning).\n"
    "- You are the decision model. Advisors are often wrong about details; treat their output as cheap hypotheses. "
    "When advisors agree with each other and with your world model, act with less probing. When they disagree with you, "
    "check the disputed fact in Python (`current_frame.segmentation`, `nav`) before spending actions.\n"
    "- Never copy an advisor's action list blindly; validate it against `valid_actions` and your own search or `nav.path_to`.\n"
)

SOLVER_ADDENDUM = (
    "\n\nSolver synthesis (`propose_solver(code)`, ours):\n"
    "- Acting one turn at a time is expensive. Once you believe you understand the rules and the goal of the current game, "
    "write a persistent solver instead: call `propose_solver(code)` from the python tool with a string of Python code that defines "
    "`def solve():` — it reads the same runtime variables (`current_frame`, `history`, `transitions`, `nav`, `valid_actions`) "
    "and returns the list of actions to execute next (e.g. `['UP','UP']` or `[{'action':'MOUSE','row':4,'col':7}]`); return `[]` when it cannot decide.\n"
    "- Optionally define `def predict(before_frame, action_name):` returning the expected after-board as an ascii string (same format as "
    "`current_frame.ascii`) or None. It is scored against the recorded transitions; the report tells you the accuracy and mismatching rows. "
    "A solver whose predict() is below 0.5 accuracy is rejected — fix the world model first.\n"
    "- After a successful proposal the harness runs solve() automatically on every following turn WITHOUT calling you, until solve() returns [], "
    "raises, keeps producing actions that do not change the board, or the level does not advance for a long time. Then you receive the failure "
    "report and can repair the code and propose again, or act manually.\n"
    "- Keep solve() deterministic and short; build it on `current_frame.segmentation` and `nav` (e.g. `nav.path_to(row, col)`), and prefer a "
    "search (BFS over candidate positions/orders) over hand-written action sequences. Propose as soon as the rules are clear — usually after a few probes "
    "or right after completing level 1 — because the solver also carries over to the next levels.\n"
    "- Minimal template (navigation game: visit the nearest unvisited target, else explore):\n"
    "  propose_solver('''\n"
    "  def solve():\n"
    "      if nav is None or not nav.moves:\n"
    "          return [a for a in ['UP','DOWN','LEFT','RIGHT'] if a in valid_actions][:1]\n"
    "      for t in nav.targets():\n"
    "          if not t['visited'] and t['path_len']:\n"
    "              return nav.path_to(t['row'], t['col']) or []\n"
    "      reach = [t for t in nav.targets() if t['path_len']]   # all visited: revisit the least recently visited\n"
    "      if reach:\n"
    "          t = min(reach, key=lambda t: t['last_visit'])\n"
    "          return nav.path_to(t['row'], t['col']) or []\n"
    "      fr = nav.frontier()\n"
    "      return (nav.path_to(fr[0], fr[1]) or []) if fr else []\n"
    "  ''')\n"
    "- Click-game template (no avatar; MOUSE only): sweep objects, re-click the ones whose clicks changed the board, skip HUD bars:\n"
    "  propose_solver('''\n"
    "  def solve():\n"
    "      seg = current_frame.segmentation; nodes = seg['nodes']\n"
    "      def center(n):\n"
    "          b = n['boundary']; rs = [q[0] for q in b]; cs = [q[1] for q in b]\n"
    "          return ((min(rs)+max(rs))//2, (min(cs)+max(cs))//2)\n"
    "      def hud(n):\n"
    "          b = n['boundary']; rs = [q[0] for q in b]; cs = [q[1] for q in b]\n"
    "          return (max(rs)-min(rs) <= 2 and max(cs)-min(cs) >= 24 and (min(rs) <= 1 or max(rs) >= 62)) or "
    "                 (max(cs)-min(cs) <= 2 and max(rs)-min(rs) >= 24 and (min(cs) <= 1 or max(cs) >= 62))\n"
    "      clicked = {}\n"
    "      for t in transitions:\n"
    "          m = __import__('re').search(r'row=(\\d+), col=(\\d+)', str(t.action))\n"
    "          if m:\n"
    "              key = (int(m.group(1))//4, int(m.group(2))//4)\n"
    "              changed = t.before_frame.ascii != t.after_frame.ascii\n"
    "              clicked.setdefault(key, [0, 0]); clicked[key][0] += 1; clicked[key][1] += int(changed)\n"
    "      cands = [n for n in nodes if not hud(n) and n['pixels'] <= 600]\n"
    "      cands.sort(key=lambda n: n['pixels'])\n"
    "      fresh = [n for n in cands if (center(n)[0]//4, center(n)[1]//4) not in clicked]\n"
    "      pool = fresh or [n for n in cands if clicked.get((center(n)[0]//4, center(n)[1]//4), [0, 0])[1] > 0] or cands\n"
    "      if not pool:\n"
    "          return []\n"
    "      r, c = center(pool[0])\n"
    "      return [{'action': 'MOUSE', 'row': r, 'col': c}]\n"
    "  ''')\n"
    "  Never define your own `propose_solver` — it is a built-in tool; just call it with the code string. "
    "Adapt the target choice to the rules you inferred (e.g. key before door, order by colour); for click games return "
    "[{'action':'MOUSE','row':r,'col':c}] computed from `current_frame.segmentation`.\n"
)

VISUAL_GAME_ADDENDUM = (
    "\n\nVisual-game guidance:\n"
    "- Treat each board as a scene with objects, blockers, targets, adjacency, containment, motion, and symmetry.\n"
    "- Game entities are usually be rendered as connected multi-tile shapes such as 2×2, 2×3, 3×3, or longer patterned structures. Sometime they might also be 1x1 tokens."
    "- Some games are logic or layout puzzles with no explicit player avatar or controllable sprite on the board. Do not assume a player exists; the relevant state may be an object, region, cursor, selector, or whole-board configuration.\n"
    "- Background colors are often white or gray/black-ish large regions, but not always. Verify background hypotheses by area, stability, and object boundaries rather than assuming them.\n"
    "- In many games, a long horizontal or vertical line near an edge is a timer or remaining-steps bar. It often shrinks or changes each step. If you identify such a bar, do not get distracted by it or treat it as core gameplay state unless there is concrete evidence that it interacts with the puzzle mechanics.\n"
    "A common failure mode is to mistake a segmented edge bar for clickable puzzle pieces. If a repeated strip of small blocks sits flush against the top, bottom, left, or right border and actions only change that strip while the interior board stays the same, classify it as HUD/timer state, not as an object to click through segment by segment. DON'T DO THIS!\n"
    "- Use coordinates only to target actions or describe local evidence. Do not frame the objective as reaching a specific absolute row or column.\n"
    "- Re-ground on the newest frame after any score increase or abrupt scene change; the returned board may already be the next level.\n"
    "- `WIN` means the whole game is solved. Mid-run level completion is more likely to appear as a score increase while play continues.\n"
    "- Strategies may transfer loosely across levels, but layouts and mechanics can change. Re-check the new board before repeating a plan.\n"
    "- For `MOUSE`, pass `row` and `col` integer arguments. `row` is vertical position, `col` is horizontal position.\n"
)

STRUCTURED_RUNTIME_STATE_ADDENDUM = (
    "\n\nRuntime variables inside every `python` tool call:\n"
    "- `current_frame` is a lightweight frame view for the latest environment state.\n"
    "- `current_frame` exposes only `.ascii`, `.step`, `.level`, `.shape`, and `.segmentation`.\n"
    "- `current_frame.ascii` is a single newline-delimited string containing the latest board rendered with the letter-coded ARC color symbols.\n"
    "- `current_frame.segmentation` parses the board into objects. It returns `{'nodes': [...], 'adjacency_list': [...]}`.\n"
    "- Each node in `segmentation['nodes']` is one 4-connected same-color object with: `id` (index, ordered top-most-left-most), `color` (ARC color character), `hash` (a signature of the object's color and shape that ignores its position -- equal hashes mean the same object regardless of where it is, so use it to track an object across frames or to spot multiple identical objects in one frame), `pixels` (cell count), `boundary` (clockwise outer-perimeter corner points as `[row, col]`), and `children` (ids of objects fully enclosed by this one).\n"
    "- `segmentation['adjacency_list']` is a list of `[i, j]` node-id pairs whose objects share an edge.\n"
    
    "- `current_frame.step` is the current environment step count.\n"
    "- `current_frame.level` is the current level number.\n"
    "- `current_frame.shape` is a `(rows, cols)` tuple.\n"
    "- The raw numeric grid is intentionally not exposed. Use `current_frame.segmentation` as your primary view of the board -- objects, colors, shapes, containment, adjacency, and cross-frame object hashes. Use `current_frame.ascii` only to read a small, specific region; do not scan the whole board with it.\n"

    "- `history` is a chronological list of action/frame snapshots.\n"
    "- `history` is a Python list of objects, not a dict.\n"
    "- Each history entry exposes only `.action` and `.frame`; entries are not subscriptable like `entry['action']`.\n"
    "- Each `history[i].frame` is the frame after `history[i].action`; each frame exposes only `.ascii`, `.step`, `.level`, `.shape`, and `.segmentation`.\n"
    "- Important history semantics: when `history` is non-empty, `history[-1].frame` is the same latest/post-action board as `current_frame`. It is not the previous board. To inspect the state before the latest action, use `previous_frame` or `history[-2].frame` when available.\n"
    "- `previous_frame` is the frame before the most recent real environment action, or `None` if no previous frame is available.\n"
    "- `last_action` is the most recent real environment action name/display, or `None` before any real action.\n"
    "- `last_action_frame` is the post-action frame for `last_action`; it matches `current_frame` after a real action.\n"
    "- `transitions` is a chronological list of actual action transitions, excluding the initial seeded frame. Each transition exposes `.action`, `.before_frame`, `.after_frame`, `.frame` (alias of `.after_frame`), and `.result`.\n"
    "- `last_transition` is `transitions[-1]` or `None`. Its `.result` mirrors `last_action_result`; older transitions may have an empty `.result`. For before/after diffs, compare `last_transition.before_frame` to `last_transition.after_frame`; do not compare `current_frame` to `history[-1].frame`.\n"
    "- `last_action_result` is the persisted result dict from the most recent `action(...)` call. It remains available across later Python inspection calls that do not call `action(...)`, and is `{}` before any action result exists. Read transition metadata from fields/keys such as `last_action_result['board_changed']`, `last_action_result['done']`, `last_action_result['level_completed']`, `last_action_result['game_over']`, `last_action_result['run_complete']`, `last_action_result['reward']`, and `last_action_result['valid_actions']`.\n"
    "- `valid_actions` is the current list of valid action names.\n"
    "- Call `action(actions)` to execute one or more real environment actions from Python.\n"
    "- Pass `action(actions)` a list like `['LEFT']` or `[{'action': 'MOUSE', 'row': 4, 'col': 7}]`.\n"
    "- One action usually returns one frame, but a single action can result in a short multi-frame animation.\n"
    "- After `action(actions)` returns, `current_frame`, `previous_frame`, `history`, `transitions`, `valid_actions`, and `last_action_result` are refreshed.\n"
)

MULTIMODAL_CONTEXT_ADDENDUM = (
    "\n\nMultimodal context:\n"
    "- User turns include an attached image of the current ARC grid.\n"
    "- The image and `current_frame.ascii` are two representations of the same current frame.\n"
    "- You can use images and other tools to understand the game state and guide your strategy, each may be useful depending on the current uncertainty.\n"
)

PYTHON_ADDENDUM = (
    "\n\nPython tool guidance:\n"
    "- Use `current_frame.segmentation` as your primary view of the board -- objects, colors, containment, adjacency, and cross-frame object hashes.\n"
    "- Use `current_frame.ascii` only to read a small, specific region of the board when `segmentation` is not enough; never use it to scan or summarize the whole board.\n"
    "- Every `python` tool call starts fresh. Re-import modules or re-define any custom utility logic you need.\n"
    "- The only importable standard-library modules are: bisect, collections, copy, fractions, functools, heapq, itertools, json, math, operator, random, re, statistics, string.\n"
    "- The only tool is `python`; call it with one ephemeral `code` string.\n"
    "- Always inspect `current_frame`, `history`, and `valid_actions` from Python instead of reasoning from the raw board by eye.\n"
    "- For the most recent change, compare `previous_frame` to `current_frame`, or `last_transition.before_frame` to `last_transition.after_frame`. `history[-1].frame` is the current frame, so comparing it to `current_frame` only compares the board to itself.\n"
    "- Maintain a compact working world model: what entities or regions exist, what actions seem to do, what the goal likely is, what remains uncertain, and what plan best fits the evidence so far.\n"
    "- IMPORTANT: Especially when the game is about making an agent navigate to a target, it is usually safer to write an explicit search algorithm such as BFS. More generally, when the objective is understood but the best action order is unclear, pathfinding, flood fill, BFS, DFS, beam search, shortest-path search, limited action-sequence search, or custom heuristics are all valid.\n"
    "- Optimize for the shortest reliable sequence that advances the current goal as described by your world model. If confidence is low, program a discriminating probe and revise the world model from the result.\n"
    "- Once the important state variables and action effects are sufficiently understood, stop probing and search in the inferred state space.\n"
    "- Inspect current and history frames from Python instead of describing frames freehand.\n"
    "- Never print or echo full board frames. Return only compact derived summaries such as object lists, diffs, coordinates, counts, or tiny local crops.\n"
    "- Keep tool-output context size minimal and decision-oriented so you can quickly compare before/after state. It's fine to write a lot of python code, just make the output short and interpretable\n"
    "- A strong default loop is: summarize the board, infer the desired environment change, write a small scorer or search over candidate sequences, execute the best probe or plan with `action(...)`, then inspect again until you understand exactly what changed.\n"
    "- For object tracking, match objects by color, overlap, bounding box proximity, area change, and edge contact rather than by exact coordinates alone.\n"
    "- For frame diffs, summarize changed cells, color transitions, appearing/disappearing components, movement candidates, and small local row slices around the changed region.\n"
    "- After every action, verify whether gameplay objects changed or whether only a timer, progress bar, or remaining-step bar moved. Do not treat HUD-only changes as evidence that the move worked.\n"
    "- Use `print(...)` for compact summaries, or assign a final compact object to `result`.\n"
    "- Call `action(...)` inside Python rather than returning action text in the chat.\n"
    "- `action(...)` accepts an ordered list of one or more actions. Once your code has selected a reliable sequence, it is often useful to batch it.\n"
    "- You can also call `action(...)` multiple times in one Python snippet, including inside loops. Each call updates the preloaded variables before execution continues.\n"
    "- If an action result reports `game_over`, `run_complete`, `level_completed`, or `done`, stop acting immediately and re-ground on the next turn.\n"
)

COMPACT_TOOL_SESSION_ADDENDUM = (
    "\n\nTool session rules:\n"
    "- You have exactly one tool: `python`.\n"
    f"- {TOOL_CALL_FORMAT_GUIDANCE}\n"
    "- The `python` tool code is not saved between calls, so rewrite any custom utility logic you still need.\n"
    "- You can call the `python` tool as many times as you want per step. Investigate until your code has a clear probe or plan.\n"
    "- Do not ration tool calls when the state is unclear. Spend extra tool calls to confirm what changed between frames and whether the last action affected gameplay state or only HUD elements such as countdown bars.\n"
    "- After `action(...)` returns, the structured runtime state is refreshed before the next Python statement and before the next tool call. Inspection-only Python calls do not clear `last_action_result`.\n"
    "- Each `python` tool call has a hard time limit of 30 seconds.\n"
    "- Tool responses are capped to about {tool_output_tokens} tokens. If a response is cut off, the tool result will tell you that.\n"
    "- Keep code snippets short and purpose-built rather than dumping large frameworks into one call.\n"
)
